const FontFamilyList = [
  { label: "Source code", value: `'Source code pro', monospace` },
  { label: "JetBrains", value: `'JetBrains Mono', monospace` },
  { label: "Open sans", value: `'Open Sans', sans-serif` },
  { label: "Sono", value: `'Sono', sans-serif` },
  { label: "Space Mono", value: `'Space Mono', sans-serif` },
  { label: "Poppins", value: `'Poppins', sans-serif` },
  { label: "Fira Mono", value: `'Fira Mono', monospace` },
  { label: "Ubuntu", value: `'Ubuntu', sans-serif` },
  { label: "Montserrat", value: `'Montserrat', sans-serif` },
  { label: "Oswald", value: `'Oswald', sans-serif` },
  { label: "Quicksand", value: `'Quicksand', sans-serif` },
  { label: "Roboto Mono", value: `'Roboto Mono', monospace` },
  { label: "Rubik", value: `'Rubik', sans-serif` },
  { label: "Ubuntu Mono", value: `'Ubuntu Mono', monospace` },
  { label: "Work Sans", value: `'Work Sans', sans-serif` },
  { label: "Zilla Slab", value: `'Zilla Slab', serif` },
  { label: "Lucida Console", value: `'Lucida Console', monospace` },
  { label: "Liberation Mono", value: `'Liberation Mono', monospace` },
  { label: "Hack", value: `'Hack', monospace` },
  { label: "DejaVu Sans Mono", value: `'DejaVu Sans Mono', monospace` },
  { label: "Courier New", value: `'Courier New', monospace` },
  { label: "IBM Plex Mono", value: `'IBM Plex Mono', monospace` },
  { label: "Fira Code", value: `'Fira Code', monospace` },
  { label: "Inconsolata", value: `'Inconsolata', monospace` },
  { label: "Consolas", value: `'Consolas', monospace` },
  { label: "Pragmata Pro", value: `'Pragmata Pro', monospace` },
  { label: "Terminus", value: `'Terminus', monospace` },
  { label: "Iosevka", value: `'Iosevka', monospace` },
  { label: "Anonymous Pro", value: `'Anonymous Pro', monospace` },
  { label: "Droid Sans Mono", value: `'Droid Sans Mono', monospace` },
  { label: "Input Mono", value: `'Input Mono', monospace` },
];

const PaddingList = [
  { label: "30", value: "30px" },
  { label: "50", value: "50px" },
  { label: "70", value: "70px" },
  { label: "90", value: "90px" },
  { label: "110", value: "110px" },
];

const ProgrammingLanguages = [
  { label: "JavaScript", value: "javascript" },
  { label: "Python", value: "python" },
  { label: "Java", value: "java" },
  { label: "Ruby", value: "ruby" },
  { label: "PHP", value: "php" },
  { label: "Swift", value: "swift" },
  { label: "Kotlin", value: "kotlin" },
  { label: "TypeScript", value: "typescript" },
  { label: "C#", value: "c#" },
  { label: "Go", value: "go" },
  { label: "Scala", value: "scala" },
  { label: "Rust", value: "rust" },
  { label: "Lua", value: "lua" },
  { label: "Perl", value: "perl" },
  { label: "Haskell", value: "haskell" },
  { label: "Dart", value: "dart" },
  { label: "SQL", value: "sql" },
];

const WidthList = [
  { label: "400", value: "400px" },
  { label: "500", value: "500px" },
  { label: "600", value: "600px" },
  { label: "700", value: "700px" },
  { label: "800", value: "800px" },
  { label: "900", value: "900px" },
  { label: "1000", value: "1000px" },
  { label: "1100", value: "1100px" },
  { label: "1200", value: "1200px" },
];

const FormatList = [
  { label: "PNG", value: ".png" },
  { label: "SVG", value: ".svg" },
  { label: "JPEG", value: ".jpeg" },
];

const ThemeList = [
  { label: "A11y Dark", value: "prism-a11y-dark" },
  { label: "Atom Dark", value: "prism-atom-dark" },
  { label: "Sulpher Light", value: "prism-base16-ateliersulphurpool-light" },
  { label: "Cb", value: "prism-cb" },
  { label: "Coldark Cold", value: "prism-coldark-cold" },
  { label: "Coldark Dark", value: "prism-coldark-dark" },
  { label: "Coy Without Shadows", value: "prism-coy-without-shadows" },
  { label: "Custom", value: "prism-custom" },
  { label: "Darcula", value: "prism-darcula" },
  { label: "Dracula", value: "prism-dracula" },
  { label: "Duotone Dark", value: "prism-duotone-dark" },
  { label: "Duotone Earth", value: "prism-duotone-earth" },
  { label: "Duotone Forest", value: "prism-duotone-forest" },
  { label: "Duotone Light", value: "prism-duotone-light" },
  { label: "Duotone Sea", value: "prism-duotone-sea" },
  { label: "Duotone Space", value: "prism-duotone-space" },
  { label: "Ghcolors", value: "prism-ghcolors" },
  { label: "Gruvbox Dark", value: "prism-gruvbox-dark" },
  { label: "Gruvbox Light", value: "prism-gruvbox-light" },
  { label: "Holi Theme", value: "prism-holi-theme" },
  { label: "Hopscotch", value: "prism-hopscotch" },
  { label: "Laserwave", value: "prism-laserwave" },
  { label: "Lucario", value: "prism-lucario" },
  { label: "Material Dark", value: "prism-material-dark" },
  { label: "Material Light", value: "prism-material-light" },
  { label: "Night Owl", value: "prism-night-owl" },
  { label: "Nord", value: "prism-nord" },
  { label: "One Dark", value: "prism-one-dark" },
  { label: "One Light", value: "prism-one-light" },
  { label: "Pojoaque", value: "prism-pojoaque" },
  { label: "Shades Of Purple", value: "prism-shades-of-purple" },
  { label: "Solarized Dark Atom", value: "prism-solarized-dark-atom" },
  { label: "Vs", value: "prism-vs" },
  { label: "Vsc Dark Plus", value: "prism-vsc-dark-plus" },
  { label: "Xonokai", value: "prism-xonokai" },
  { label: "Z Touch", value: "prism-z-touch" },
];

export {
  ThemeList,
  FontFamilyList,
  PaddingList,
  ProgrammingLanguages,
  WidthList,
  FormatList,
};
